"use client";

import React, { useState, useEffect } from "react";
import { CheckSquare, Square, CalendarDays, Droplet, Leaf, Sprout, ShieldAlert, Plus } from "lucide-react";

export default function TaskPlanner() {
  const [tasks, setTasks] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetchTasks();
  }, []);

  const fetchTasks = () => {
    fetch("/api/v1/tasks?farm_id=1")
      .then((res) => res.json())
      .then((data) => {
        // Sort: pending first, then by due date
        setTasks(data);
        setLoading(false);
      })
      .catch((err) => {
        console.error("Error loading tasks", err);
        setLoading(false);
      });
  };

  const handleToggleStatus = (taskId: number, currentStatus: string) => {
    const nextStatus = currentStatus === "completed" ? "pending" : "completed";
    
    fetch(`/api/v1/tasks/${taskId}`, {
      method: "PUT",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify({ status: nextStatus })
    })
      .then((res) => res.json())
      .then(() => {
        // Update local state
        setTasks(tasks.map(t => t.id === taskId ? { ...t, status: nextStatus } : t));
      })
      .catch((err) => console.error("Error updating task status", err));
  };

  const getCategoryIcon = (cat: string) => {
    switch (cat.toLowerCase()) {
      case "watering":
        return <Droplet className="text-blue-500" size={18} />;
      case "fertilizer":
        return <Leaf className="text-emerald-500" size={18} />;
      case "treatment":
        return <ShieldAlert className="text-red-500" size={18} />;
      default:
        return <Sprout className="text-teal-500" size={18} />;
    }
  };

  return (
    <div className="space-y-8">
      {/* Title */}
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <h1 className="text-3xl font-bold tracking-tight">Task Planner</h1>
          <p className="text-sm text-gray-500 dark:text-slate-400">Manage daily and weekly agricultural operations generated by the Crop Planning Agent.</p>
        </div>
      </div>

      {loading ? (
        <div className="flex justify-center items-center min-h-[40vh]">
          <div className="w-10 h-10 border-4 border-teal-500 border-t-transparent rounded-full animate-spin"></div>
        </div>
      ) : (
        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
          {/* Main Task List */}
          <div className="lg:col-span-2 glass-panel p-6 rounded-2xl space-y-4">
            <h3 className="font-semibold text-lg flex items-center gap-2">
              <CalendarDays className="text-teal-600" /> Active Schedules
            </h3>
            
            <div className="space-y-3">
              {tasks.length > 0 ? (
                tasks.map((task) => (
                  <div
                    key={task.id}
                    className={`flex items-center justify-between p-4 rounded-xl border border-border transition-all duration-200 ${
                      task.status === "completed" 
                        ? "bg-slate-100/40 dark:bg-slate-900/20 opacity-60" 
                        : "bg-white/40 dark:bg-slate-900/40 hover:bg-white/70 dark:hover:bg-slate-900/70"
                    }`}
                  >
                    <div className="flex items-start gap-4">
                      <button 
                        onClick={() => handleToggleStatus(task.id, task.status)}
                        className="mt-0.5 text-gray-400 hover:text-teal-600 transition-colors"
                      >
                        {task.status === "completed" ? (
                          <CheckSquare className="text-teal-600" size={20} />
                        ) : (
                          <Square size={20} />
                        )}
                      </button>
                      <div className="space-y-0.5">
                        <p className={`text-sm font-semibold ${task.status === "completed" ? "line-through" : ""}`}>
                          {task.title}
                        </p>
                        <p className="text-xs text-gray-500 leading-relaxed font-light">{task.description}</p>
                        <div className="flex gap-4 pt-1">
                          <span className="text-[10px] font-bold uppercase tracking-wider text-gray-400">
                            Due: {new Date(task.due_date).toLocaleDateString()}
                          </span>
                        </div>
                      </div>
                    </div>
                    
                    <div className="p-2 rounded-xl bg-slate-100 dark:bg-slate-800 border border-border">
                      {getCategoryIcon(task.category)}
                    </div>
                  </div>
                ))
              ) : (
                <div className="text-center py-12 text-gray-400 text-xs font-light">
                  No tasks scheduled. Run the image scanner or speak with the assistant to generate tasks.
                </div>
              )}
            </div>
          </div>

          {/* Quick Guide Card */}
          <div className="glass-panel p-6 rounded-2xl space-y-4 h-fit">
            <h3 className="font-semibold text-base">Crop Rotation & Long-Term Advice</h3>
            <div className="p-4 rounded-xl bg-teal-500/10 border border-teal-500/20 text-xs leading-relaxed text-gray-600 dark:text-slate-300">
              <p className="font-bold text-teal-700 dark:text-teal-400 uppercase tracking-wider mb-2">AGRONOMIST TIP</p>
              After harvesting your current Tomato crop, the Planning Agent recommends planting <b>Legumes (e.g., Beans or Peas)</b>. This will naturally restore nitrogen levels in the soil, reducing your chemical fertilizer requirements by up to 30% next season.
            </div>
          </div>
        </div>
      )}
    </div>
  );
}
